# Generated by Django 4.0.3 on 2022-03-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugreaction',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='meml.drug'),
            preserve_default=False,
        ),
    ]
