# Generated by Django 4.0.3 on 2022-03-20 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meml', '0002_drugreaction_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugreaction',
            name='drug_one',
        ),
    ]
