# Generated by Django 4.0.3 on 2022-03-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meml', '0003_remove_drugreaction_drug_one'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginteraction',
            old_name='reaction',
            new_name='drug_interaction',
        ),
        migrations.RemoveField(
            model_name='drugreaction',
            name='drug_two',
        ),
        migrations.AddField(
            model_name='druginteraction',
            name='drug_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drug_two', to='meml.drug'),
            preserve_default=False,
        ),
    ]
