# Generated by Django 4.0.3 on 2022-03-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meml', '0004_rename_reaction_druginteraction_drug_interaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginteraction',
            old_name='drug_interaction',
            new_name='drug_reaction',
        ),
    ]
